config/routes.rb
Project::Application.routes.draw do

  root :to => "sessions#new"

  get 'login' => 'sessions#new', :as => :login
  get 'logout' => 'sessions#destroy', :as => :logout
  get 'welcome' => 'welcome#index', :as => :welcome

  match '/sessions/create', to: 'sessions#create'

  resources :comics, :departs, :zq_loc_grid_tree_tmps,  :yth_grid_report_charges, :marketing_real_time_daily_incomes, \
            :group_revenue_department_real_time_dailys, :shift_network_prepaid_development_dailys, \
            :daily_fixed_line_broadband_developments,   :after_shifting_network_user_development_fee_details, \
            :development_prepaid_user_details,          :pay_day_after_tracking_tables,\
            :prepaid_day_tracking_tables,               :sessions

end

app/models/marketing_real_time_daily_income.rb
class MarketingRealTimeDailyIncome < ActiveRecord::Base
  # attr_accessible :title, :body
  self.table_name = 'sssr_sc_dayreport_yth'
  def self.get_pages(key, index, size, sort_field, sort_order)

    sql =<<SQL
        select aa.flag_code       ,
               aa.timest          ,
               aa.flag_name       ,
               aa.income_mobile_d ,
               aa.income_ydhff_d  ,
               aa.income_ydyff_d  ,
               aa.income_gw_d     ,
               aa.income_kd_d     ,
               aa.income_mobile_m income_mobile_m1,
               aa.income_ydhff_m  income_ydhff_m1,
               aa.income_ydyff_m  income_ydyff_m1,
               aa.income_gw_m     income_gw_m1,
               aa.income_kd_m     income_kd_m1,
               bb.income_mobile_m income_mobile_m2,
               bb.income_ydhff_m  income_ydhff_m2,
               bb.income_ydyff_m  income_ydyff_m2,
               bb.income_gw_m     income_gw_m2,
               bb.income_kd_m     income_kd_m2
          from (select a.timest,
                       a.flag_code,
                       a.flag_name,
                       a.income_mobile_d,
                       a.income_ydhff_d,
                       a.income_ydyff_d,
                       a.income_gw_d,
                       a.income_kd_d,
                       a.income_mobile_m,
                       a.income_ydhff_m,
                       a.income_ydyff_m,
                       a.income_gw_m,
                       a.income_kd_m
                  from dc.sssr_sc_dayreport_yth a 
                ) aa,
               (select a.timest,
                       a.flag_code,
                       a.flag_name,
                       a.income_mobile_m,
                       a.income_ydhff_m,
                       a.income_ydyff_m,
                       a.income_gw_m,
                       a.income_kd_m
                  from dc.sssr_sc_dayreport_yth a
                 where a.timest = to_char(add_months(sysdate - 1, -1), 'yyyymm') ||
                       to_char(sysdate - 1, 'dd')) bb
         where aa.flag_name = bb.flag_name(+)
           and aa.flag_code = bb.flag_code(+)
SQL
    if key.blank?
      sql += " and aa.timest = to_char(sysdate - 2, 'yyyymmdd') order by #{sort_field} #{sort_order}"
    else
      sql += " and aa.timest = #{key} order by #{sort_field} #{sort_order}"
    end
    @marketing_real_time_daily_incomes = MarketingRealTimeDailyIncome.find_by_sql(sql)
    return @marketing_real_time_daily_incomes.count, @marketing_real_time_daily_incomes[index.to_i*size.to_i..index.to_i*size.to_i+size.to_i-1]
  end


end

app/controllers/marketing_real_time_daily_incomes_controller.rb
class MarketingRealTimeDailyIncomesController < ApplicationController
  # GET /marketing_real_time_daily_incomes
  # GET /marketing_real_time_daily_incomes.json
  def index
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @marketing_real_time_daily_incomes.to_xml}
      format.json do
        @count, @marketing_real_time_daily_incomes = MarketingRealTimeDailyIncome.get_pages(params[:key],params[:pageIndex], params[:pageSize],params[:sortField], params[:sortOrder])
        @result = {total: @count, data: @marketing_real_time_daily_incomes}
        render json: @result
      end
    end
  end
end

app/views/marketing_real_time_daily_incomes/index.html.erb
    <div style="width:99%;">
        <div class="mini-toolbar" style="border-bottom:0;padding:0px;">
            <table style="width:100%;">
                <tr>
                    <td style="width:100%;">      
                    </td>
                    <td style="white-space:nowrap;">
                        <input id="key" Format="yyyyMMdd" class="mini-datepicker"/>
                        <a class="mini-button" onclick="search()">查询</a>
                    </td>
                </tr>
            </table>           
        </div>
    </div>
    <div id="datagrid1" class="mini-datagrid" style="width:99%;height:95%;" allowResize="true"
         url="<%= marketing_real_time_daily_incomes_path %>.json"  idField="timest" multiSelect="true"
         sizeList="[10,20,30,50]" pageSize="10" >
        <div property="columns">
            <!--  <div type="indexcolumn"></div>  -->
            <div type="checkcolumn" ></div>      
            <div field="timest" width="120" headerAlign="center" allowSort="true">统计日期</div>  
            <div field="flag_name" width="120" headerAlign="center" allowSort="true">线条/区县</div>  
            <div field="income_mobile_d" width="120" headerAlign="center" allowSort="true">移动业务当日</div>    
            <div field="income_ydhff_d" width="120" headerAlign="center" allowSort="true">其中：后付费当日</div>    
            <div field="income_ydyff_d" width="120" headerAlign="center" allowSort="true">其中：预付费当日</div>    
            <div field="income_gw_d" width="120" headerAlign="center" allowSort="true">固网业务当日</div>    
            <div field="income_kd_d" width="120" headerAlign="center" allowSort="true">其中：宽带当日</div>    
            <div field="income_mobile_m1" width="120" headerAlign="center" allowSort="true">移动业务当月</div>    
            <div field="income_ydhff_m1" width="120" headerAlign="center" allowSort="true">其中：后付费当月</div> 
            <div field="income_ydyff_m1" width="120" headerAlign="center" allowSort="true">其中：预付费当月</div> 
            <div field="income_gw_m1" width="120" headerAlign="center" allowSort="true">固网业务当月</div>    
            <div field="income_kd_m1" width="120" headerAlign="center" allowSort="true">其中：宽带当月</div>  
            <div field="income_mobile_m2" width="120" headerAlign="center" allowSort="true">移动业务上月同期</div>
            <div field="income_mobile_m2" width="120" headerAlign="center" allowSort="true">其中：后付费上月同期</div> 
            <div field="income_ydyff_m2" width="120" headerAlign="center" allowSort="true">其中：预付费上月同期</div> 
            <div field="income_gw_m2" width="120" headerAlign="center" allowSort="true">固网业务上月同期</div> 
            <div field="income_kd_m2" width="120" headerAlign="center" allowSort="true">其中：宽带上月同期</div>       
        </div>                     
    </div>


    <script type="text/javascript">
        
        mini.parse();
        
        var grid = mini.get("datagrid1");

        grid.load();
        
        grid.sortBy('timest', 'asc');

        function search() {
            var key = mini.get("key").getFormValue();
            grid.load({ key: key });
        }
 

        
    </script>