config/routes.rb
Project::Application.routes.draw do

  root :to => "sessions#new"

  get 'login' => 'sessions#new', :as => :login
  get 'logout' => 'sessions#destroy', :as => :logout
  get 'welcome' => 'welcome#index', :as => :welcome

  match '/sessions/create', to: 'sessions#create'

  resources :comics, :departs, :zq_loc_grid_tree_tmps,  :yth_grid_report_charges, :marketing_real_time_daily_incomes, \
            :group_revenue_department_real_time_dailys, :shift_network_prepaid_development_dailys, \
            :daily_fixed_line_broadband_developments,   :after_shifting_network_user_development_fee_details, \
            :development_prepaid_user_details,          :pay_day_after_tracking_tables,\
            :prepaid_day_tracking_tables,               :sessions

end

app/models/yth_grid_report_charge.rb
# encoding: UTF-8
class YthGridReportCharge < ActiveRecord::Base

  attr_accessible :area_name, :yf_name, :grid_name, :jcdy_name, :product_name

  self.table_name='dc.yth_grid_report_charge'

  def self.get_my_value(key,index,size,sort_field,sort_order,is_all)
    if key.nil? or key == ''
      @yth_grid_report_charges = YthGridReportCharge.order("yth_grid_report_charge.#{sort_field} #{sort_order}").all \
                               if YthGridReportCharge.column_names.include?(sort_field)
    else
      @yth_grid_report_charges = YthGridReportCharge.where('yf_name like ?', "%#{key}%") \
                               .order("yth_grid_report_charge.#{sort_field} #{sort_order}") \
                               if YthGridReportCharge.column_names.include?(sort_field)
    end

    if is_all
      return @yth_grid_report_charges
    else
      return @yth_grid_report_charges.count, @yth_grid_report_charges[index.to_i*size.to_i..index.to_i*size.to_i+size.to_i-1]
    end
  end
end

app/controllers/yth_grid_report_charges_controller.rb
# encoding: UTF-8
class YthGridReportChargesController < ApplicationController
  # GET /yth_grid_report_charges
  # GET /yth_grid_report_charges.json
  def index
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @zq_loc_grid_tree_tmps.to_xml}
      format.json do
        @count, @yth_grid_report_charges = YthGridReportCharge.get_my_value(params[:key], \
                                                                 params[:pageIndex], params[:pageSize], \
                                                                 params[:sortField], params[:sortOrder],false)
        @result = {total: @count, data: @yth_grid_report_charges}
        render json: @result
      end
    end
  end
end

app/views/yth_grid_report_charges/index.html.erb
    <div style="width:99%;">
        <div class="mini-toolbar" style="border-bottom:0;padding:0px;">
            <table style="width:100%;">
                <tr>
                    <td style="width:100%;">      
                    </td>
                    <td style="white-space:nowrap;">
                        <input type="text" id="key" placeholder="请输入营服中心名字" style="width:150px;" />
                        <a class="mini-button" onclick="search()">查询</a>
                    </td>
                </tr>
            </table>           
        </div>
    </div>
    <div id="datagrid1" class="mini-datagrid" style="width:99%;height:95%;" allowResize="true"
         url="<%= yth_grid_report_charges_path %>.json"  idField="yf_name" multiSelect="true"
         sizeList="[10,20,30,50]" pageSize="10" >
        <div property="columns">
            <!--<div type="indexcolumn"></div>        -->
            <div type="checkcolumn" ></div>        
            <div field="area_name" width="120" headerAlign="center" allowSort="true">范围</div>    
            <div field="yf_name" width="120" headerAlign="center" allowSort="true">营服中心</div>    
            <div field="grid_name" width="120" headerAlign="center" allowSort="true">团队</div>    
            <div field="jcdy_name" width="120" headerAlign="center" allowSort="true">客户</div> 
            <div field="product_name" width="120" headerAlign="center" allowSort="true">产品</div>    
            <div field="sum_charge" width="120" headerAlign="center" allowSort="true">总计</div> 
            </div>                     
        </div>


    <script type="text/javascript">
        
        mini.parse();
        
        var grid = mini.get("datagrid1");

        grid.load();
        
        grid.sortBy('sum_charge', 'asc');

        function search() {
            var key = document.getElementById("key").value;
            grid.load({ key: key });
        }
 

        
    </script>




    